In [4]:
import numpy as np
marks=np.array([80,40,30,89])
print(marks)

import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+b)

import numpy as np
a=np.array([8,9,10])
b=np.array([5,6,7])
print(a-b)

import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a*b)

import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a/b)

[80 40 30 89]
[ 6  8 10]
[3 3 3]
[ 5 12 21]
[0.2        0.33333333 0.42857143]
